[package]
name = "bcirc"
version = "0.1.0"
repository = "https://github.com/marshray/bcirc"
license = "MIT OR Apache-2.0"
publish = false
edition = "2024"

#========================================== Dependencies ==========================================|
[dependencies]

anyhow = "1.0.98"
# ariadne = "0.3"
bitvec = { version = "1.0.1", features = ["serde"] }
# bumpalo =  { version = "3.18.1", features = ["allocator_api"] }
chumsky = { version = "0.10.1", default-features = false, features = [
    "nightly",
    "std",
    "serde",
] }
# deku = "0.16.0"
either = { version = "1.15.0", default-features = false, features = [] }
# itertools = { version = "0.14.0", default-features = false, features = [] }
memmap2 = "0.9.5"
# ron = "0.10.1"
self_cell = "1.2.0"
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "2.0.12"

#====================================== Dev-Dependencies ==========================================|
[dev-dependencies]
#  insta.workspace = true
insta = { version = "1.43.1", default-features = false, features = ["glob", "redactions", "ron"] }

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
